### ISSUE TITLE
"Android app crashes and terminates due to an issue with the Survicate library."

### ISSUE THREAD

**Issue by SungilJung** [Survicate/survicate-react-native-sdk#62]
library info:
- "@survicate/react-native-survicate": "3.0.3",
- "@types/survicate__react-native-survicate": "1.1.0",

Device Info: Galaxy A53 5G
Android OS: 13

Error Log
`FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: , PID: 22424
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                                    	at com.survicate.surveys.PersistenceManager.addOrReplaceTraitsValues(PersistenceManager.java:154)
                                                                                                    	at com.survicate.surveys.PersistenceManager.saveTraits(PersistenceManager.java:140)
                                                                                                    	at com.survicate.surveys.Survicate.setUserTraits(Survicate.java:91)
                                                                                                    	at com.survicate.surveys.Survicate.setUserTrait(Survicate.java:101)
                                                                                                    	at com.survicate.react.SurvicateBindingsModule.setUserId(SurvicateBindingsModule.java:41)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by choudlet** [comment]
I'm seeing this same issue and getting this specific error:

Exception java.lang.IllegalStateException: Workspace key cannot be set after the SDK initialization.
  at com.survicate.surveys.Survicate.setWorkspaceKey (Survicate.java:180)
  at com.survicate.react.SurvicateModuleImpl.setWorkspaceKey (SurvicateModuleImpl.java:68)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop (Looper.java:240)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:228)
  at java.lang.Thread.run (Thread.java:923)
  
  This is only happening on APKs that I build and distribute through the google play store. Any idea on how to get around this?

**Comment by SurvicatePawelGodlewski** [comment]
@SungilJung The issue has been addressed in v3.1.1

**Comment by SurvicatePawelGodlewski** [comment]
I am closing this issue due to issue being resolved and no issue resurface
